// User Profile Types
export interface UserProfile {
  id: string;
  firstName: string;
  lastName: string;
  name: string;
  email: string;
  phone: string;
  bio: string;
  location: string;
  company: string;
  position: string;
  title: string;
  website: string;
  linkedIn: string;
  twitter?: string;
  avatar?: string;
  university: string;
  graduationYear: string;
  program: string;
  skills: string[];
  expertise: string[];
  role: 'mentor' | 'professional' | 'alumni' | 'student' | 'researcher' | 'entrepreneur';
  experience: number;
  isVerified: boolean;
  isOnline: boolean;
  lastActive: string;
  interests: string[];
  mutualConnections: number;
  responseRate: number;
  isDiaspora: boolean;
  diasporaLocation?: string;
  homeCountry?: string;
  availability: {
    mentoring: boolean;
    collaboration: boolean;
    consultation: boolean;
    volunteering?: boolean;
    speaking?: boolean;
    advising?: boolean;
  };
  openTo: string[];
  socialLinks: {
    linkedin?: string;
    twitter?: string;
    email?: string;
    website?: string;
  };
  achievements: {
    title: string;
    description: string;
    date: string;
  }[];
  universities: {
    name: string;
    role: string;
    isVerified: boolean;
  }[];
  privacy: {
    profileVisibility: 'public' | 'alumni' | 'private';
    contactVisibility: 'public' | 'alumni' | 'private';
    professionalVisibility: 'public' | 'alumni' | 'private';
  };
  preferences: {
    language: string;
    timezone: string;
    theme: 'light' | 'dark' | 'system';
  };
  password?: string; // Only for internal use, never returned in API
  createdAt: string;
  updatedAt: string;
}

// Feed Types
export interface FeedItem {
  id: string;
  type: 'project' | 'campaign' | 'opportunity' | 'milestone' | 'success_story' | 
        'funding_success' | 'live_event' | 'workroom_live' | 'project_closing' | 
        'admin_highlight' | 'achievement' | 'certification' | 'collaboration';
  title: string;
  description?: string;
  timestamp: string;
  likes: number;
  location: string;
  category: string;
  urgent?: boolean;
  deadline?: string;
  isLive?: boolean;
  isPinned?: boolean;
  isAdminCurated?: boolean;
  authorId: string;
  authorName: string;
  authorAvatar?: string;
  projectId?: string;
  campaignId?: string;
  opportunityId?: string;
  metadata?: Record<string, any>;
  visibility: 'public' | 'authenticated' | 'private';
  significance: 'low' | 'medium' | 'high' | 'critical';
  isAutoGenerated?: boolean;
}

export interface UserAction {
  id: string;
  userId: string;
  userName: string;
  userAvatar?: string;
  userLocation?: string;
  actionType: 'project_created' | 'project_joined' | 'project_completed' | 
              'campaign_launched' | 'campaign_joined' | 'milestone_achieved' | 
              'opportunity_posted' | 'opportunity_applied' | 'funding_received' | 
              'session_started' | 'session_completed' | 'certification_earned' | 
              'achievement_unlocked' | 'collaboration_started' | 'mentor_match' | 
              'workspace_created';
  entityId: string;
  entityType: 'project' | 'campaign' | 'opportunity' | 'session' | 
              'certification' | 'achievement' | 'workspace' | 'collaboration';
  entityTitle: string;
  entityCategory: string;
  timestamp: string;
  metadata?: Record<string, any>;
  visibility?: 'public' | 'authenticated' | 'private';
}

export interface AdminHighlight {
  id: string;
  type: 'top_mentor' | 'spotlighted_opportunity' | 'impact_stat' | 
        'featured_project' | 'announcement' | 'success_spotlight' | 
        'community_milestone';
  title: string;
  description: string;
  image?: string;
  ctaText?: string;
  ctaLink?: string;
  isPinned: boolean;
  expiresAt?: string;
  createdBy: string;
  createdAt: string;
  visibility: 'public' | 'authenticated';
  projectId?: string;
  opportunityId?: string;
}

// Project Types
export interface Project {
  id: string;
  title: string;
  description: string;
  status: 'active' | 'still-open' | 'closed';
  startDate: string;
  deadline?: string;
  closedDate?: string;
  category: string;
  aspiraCategory: 'mentorships' | 'university-campaigns' | 'community-service' | 'research';
  tags: string[];
  team: Array<{
    id: string;
    name: string;
    role: string;
    avatar?: string;
  }>;
  university: string;
  location: string;
  authorId: string;
  authorName: string;
  projectType?: 'mentorship' | 'academic' | 'career' | 'community' | 'collaboration';
  priority?: 'low' | 'medium' | 'high';
  mentorshipConnection?: boolean;
  isPublic?: boolean;
  teamMembers?: TeamMember[];
  diasporaPositions?: DiasporaPosition[];
  progress?: number;
  metrics?: {
    tasksCompleted: number;
    totalTasks: number;
    milestonesHit: number;
    totalMilestones: number;
    participantsReached: number;
    impactScore: number;
  };
  createdAt: string;
  updatedAt: string;
}

export interface TeamMember {
  id: string;
  name: string;
  email: string;
  role: string;
  avatar?: string;
}

export interface DiasporaPosition {
  id: string;
  title: string;
  description: string;
  responsibilities: string[];
  requirements: string[];
  commitment: string;
  category: 'leadership' | 'technical' | 'advisory' | 'mentorship' | 'support';
}

export interface Task {
  id: string;
  projectId: string;
  title: string;
  description?: string;
  status: 'todo' | 'in-progress' | 'done';
  priority: 'low' | 'medium' | 'high';
  assignee: string; // User ID or name
  assignedDate: string;
  dueDate?: string;
  completedDate?: string;
  comments: Array<{
    id: string;
    author: string;
    authorAvatar?: string;
    content: string;
    timestamp: string;
  }>;
  attachments: Array<{
    id: string;
    name: string;
    size: number;
    type: string;
    url: string;
  }>;
  tags?: string[];
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface Milestone {
  id: string;
  projectId: string;
  title: string;
  description: string;
  dueDate: string;
  status: 'upcoming' | 'in-progress' | 'completed';
  progress: number;
  tasks: string[];
  source: string;
  lastUpdated: string;
  createdAt: string;
}

// Opportunity Types
export interface Opportunity {
  id: string;
  title: string;
  type: 'scholarship' | 'job' | 'internship' | 'fellowship' | 'accelerator' | 
        'grant' | 'event' | 'community' | 'others';
  company: string;
  location: string;
  remote: boolean;
  description: string;
  requirements?: string[];
  benefits?: string[];
  amount?: {
    value: number;
    currency: string;
    type: 'salary' | 'stipend' | 'award' | 'funding';
  };
  duration?: string;
  commitment?: string;
  postedBy: {
    name: string;
    title: string;
    company: string;
    avatar?: string;
    isVerified: boolean;
  };
  university?: string;
  tags: string[];
  applicants: number;
  deadline?: string;
  eventDate?: string;
  postedDate: string;
  featured: boolean;
  urgent: boolean;
  boost: number;
  saved: boolean;
  applied: boolean;
  experienceLevel: 'entry' | 'mid' | 'senior' | 'any';
  category: string;
  eligibility?: string[];
  applicationLink?: string;
  comments: number;
  fullDescription?: string;
  applicationProcess?: string[];
  contactInfo?: {
    email?: string;
    phone?: string;
    website?: string;
  };
  createdAt: string;
  updatedAt: string;
}

// Network Types
export interface NetworkUser {
  id: string;
  name: string;
  avatar?: string;
  title: string;
  company: string;
  location: string;
  university: string;
  graduationYear: string;
  program: string;
  bio: string;
  skills: string[];
  expertise: string[];
  role: 'mentor' | 'professional' | 'alumni' | 'student' | 'researcher' | 'entrepreneur';
  experience: number;
  connectionStatus: 'none' | 'pending_sent' | 'pending_received' | 'connected';
  mutualConnections: number;
  responseRate: number;
  isVerified: boolean;
  isOnline: boolean;
  lastActive: string;
  interests: string[];
  socialLinks?: {
    linkedin?: string;
    twitter?: string;
    email?: string;
  };
  achievements?: {
    title: string;
    description: string;
    date: string;
  }[];
  availability?: {
    mentoring: boolean;
    collaboration: boolean;
    consultation: boolean;
    volunteering?: boolean;
    speaking?: boolean;
    advising?: boolean;
  };
  openTo?: string[];
}

export interface ConnectionRequest {
  id: string;
  fromUserId: string;
  fromUserName: string;
  fromUserAvatar?: string;
  fromUserTitle: string;
  fromUserCompany: string;
  toUserId: string;
  purpose: string;
  message: string;
  timestamp: string;
  status: 'pending' | 'accepted' | 'declined';
}

// Campaign Types
export interface Campaign {
  id: string;
  title: string;
  description: string;
  type: 'mentorship' | 'research' | 'education' | 'community';
  status: 'active' | 'upcoming' | 'completed';
  university: string;
  category: string;
  startDate: string;
  endDate: string;
  location: string;
  isRemote: boolean;
  participantGoal: number;
  currentParticipants: number;
  fundingGoal: number;
  currentFunding: number;
  tags: string[];
  createdBy: {
    id: string;
    name: string;
    avatar?: string;
  };
  image?: string;
  spotsRemaining?: number;
  createdAt: string;
  updatedAt: string;
}

// Workspace Types
export interface ProjectMember {
  id: string;
  name: string;
  email: string;
  avatar?: string;
  role: 'owner' | 'admin' | 'mentor' | 'student' | 'collaborator' | 'viewer' | 
        'mentee' | 'participant' | 'leader' | 'researcher';
  status: 'active' | 'pending' | 'inactive' | 'completed' | 'paused';
  joinedDate: string;
  lastActive: string;
  skills?: string[];
  university?: string;
  program?: string;
  year?: string;
  isOnline?: boolean;
  tasksCompleted?: number;
  contributionScore?: number;
  projectsInvolved?: number;
  progress?: number;
}

export interface Session {
  id: string;
  projectId: string;
  title: string;
  description?: string;
  scheduledDate: string; // ISO date string
  duration: number; // in minutes
  status: 'upcoming' | 'in-progress' | 'completed' | 'cancelled' | 'rescheduled';
  type: 'video' | 'phone' | 'in-person';
  meetingLink?: string;
  location?: string;
  agenda?: string[];
  notes?: string;
  recordings?: Array<{ url: string; title: string; duration: number }>;
  attendees: Array<{ name: string; avatar?: string; attended?: boolean; userId: string }>;
  isPublic?: boolean;
  tags?: string[];
  maxParticipants?: number;
  shareUrl?: string;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface Message {
  id: string;
  senderId: string;
  senderName: string;
  senderAvatar?: string;
  recipientId?: string;
  projectId?: string;
  content: string;
  timestamp: string;
  type: 'text' | 'voice' | 'file';
  duration?: number; // for voice messages in seconds
  fileUrl?: string;
  fileName?: string;
  fileSize?: number;
  isRead: boolean;
  edited?: boolean;
}

export interface VoiceNote {
  id: string;
  title: string;
  duration: number;
  url: string;
  timestamp: string;
  sender: string;
  senderAvatar?: string;
  projectId?: string;
  tags?: string[];
  transcript?: string;
}

// File Upload Types
export interface UploadedFile {
  id: string;
  filename: string;
  originalName: string;
  url: string;
  thumbnailUrl?: string;
  type: string;
  size: number;
  duration?: number; // for video/audio
  status: 'processing' | 'ready' | 'failed';
  uploadedBy: string;
  uploadedAt: string;
}

// Auth Types
export interface AuthTokens {
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface RegisterRequest {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
}

// Learning Vault Types
export interface LearningContent {
  id: string;
  projectId: string;
  title: string;
  description: string;
  type: 'video' | 'document' | 'quiz' | 'assignment' | 'recording';
  category: 'orientation' | 'skills' | 'reflections' | 'tools' | 'recordings';
  duration?: number;
  thumbnail?: string;
  url: string;
  progress: number;
  rating?: number;
  uploadDate: string;
  lastAccessed?: string;
  tags: string[];
  size?: number;
  status?: 'processing' | 'ready' | 'failed';
  uploadedBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface Recording {
  id: string;
  projectId: string;
  title: string;
  description?: string;
  duration: number; // in seconds
  url: string;
  thumbnail?: string;
  timestamp: string;
  type: 'screen' | 'webcam' | 'both';
  tags?: string[];
  size: number; // in bytes
  status: 'processing' | 'ready' | 'failed';
  uploadedBy: string;
  createdAt: string;
}

// Deliverables Types
export interface Deliverable {
  id: string;
  projectId: string;
  title: string;
  description: string;
  status: 'pending' | 'approved' | 'needs-revision';
  submittedDate: string;
  fileName: string;
  fileSize: number;
  fileUrl: string;
  feedback?: string;
  submittedBy: string;
  reviewedBy?: string;
  reviewedAt?: string;
  createdAt: string;
  updatedAt: string;
}

// Certificate Types
export interface Certificate {
  id: string;
  projectId: string;
  title: string;
  type: 'completion' | 'achievement' | 'milestone';
  status: 'draft' | 'ready' | 'issued';
  progress: number;
  requiredSessions: number;
  completedSessions: number;
  requiredTasks: number;
  completedTasks: number;
  issueDate?: string;
  issuedTo: string;
  issuedBy: string;
  createdAt: string;
  updatedAt: string;
}

// Live Session Types
export interface LiveSession {
  id: string;
  projectId: string;
  title: string;
  description?: string;
  sessionTitle?: string;
  sessionDescription?: string;
  isHost: boolean;
  participants: Array<{
    id: string;
    name: string;
    avatar?: string;
    isMuted: boolean;
    hasVideo: boolean;
    isCurrentUser?: boolean;
    role: 'mentor' | 'mentee' | 'participant';
    isOnline: boolean;
  }>;
  chatMessages: Array<{
    id: string;
    sender: string;
    message: string;
    timestamp: string;
    avatar?: string;
    isCurrentUser?: boolean;
    type?: 'message' | 'system';
  }>;
  startedAt?: string;
  endedAt?: string;
  status: 'scheduled' | 'active' | 'ended';
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

// Research Tools Types
export interface ResearchSource {
  id: string;
  projectId: string;
  title: string;
  authors: string[];
  year: number;
  type: 'journal' | 'conference' | 'book' | 'report' | 'website' | 'thesis';
  url?: string;
  abstract?: string;
  keywords: string[];
  relevance: number;
  notes?: string;
  addedBy: string;
  addedDate: string;
  favorite: boolean;
  citations?: number;
  doi?: string;
  createdAt: string;
  updatedAt: string;
}

export interface ResearchNote {
  id: string;
  projectId: string;
  title: string;
  content: string;
  tags: string[];
  author: string;
  createdDate: string;
  lastModified: string;
  sourceId?: string;
  shared: boolean;
  category: 'hypothesis' | 'observation' | 'methodology' | 'insight' | 'todo' | 'question';
  createdAt: string;
  updatedAt: string;
}

export interface DataSet {
  id: string;
  projectId: string;
  name: string;
  description: string;
  type: 'survey' | 'experimental' | 'observational' | 'secondary' | 'qualitative';
  size: number;
  format: string;
  uploadedBy: string;
  uploadedDate: string;
  tags: string[];
  public: boolean;
  url?: string;
  createdAt: string;
  updatedAt: string;
}

// Community Tools Types
export interface Stakeholder {
  id: string;
  projectId: string;
  name: string;
  organization: string;
  role: string;
  type: 'community-leader' | 'government' | 'ngo' | 'business' | 'academic' | 'beneficiary';
  contactInfo: {
    email?: string;
    phone?: string;
    address?: string;
  };
  influence: number;
  interest: number;
  engagement: 'high' | 'medium' | 'low';
  notes?: string;
  lastContact?: string;
  avatar?: string;
  createdAt: string;
  updatedAt: string;
}

export interface ImpactStory {
  id: string;
  projectId: string;
  title: string;
  description: string;
  category: 'education' | 'health' | 'economic' | 'social' | 'environment';
  author: string;
  authorAvatar?: string;
  location: string;
  date: string;
  beneficiaries: number;
  metrics: {
    reach: number;
    satisfaction: number;
    sustainability: number;
  };
  media: string[];
  tags: string[];
  isVerified: boolean;
  likes: number;
  shares: number;
  createdAt: string;
  updatedAt: string;
}

export interface CommunityEvent {
  id: string;
  projectId: string;
  title: string;
  description: string;
  type: 'workshop' | 'meeting' | 'outreach' | 'celebration' | 'training';
  date: string;
  time: string;
  location: string;
  organizer: string;
  attendees: number;
  maxAttendees: number;
  status: 'upcoming' | 'ongoing' | 'completed' | 'cancelled';
  requirements?: string[];
  isRegistered: boolean;
  createdAt: string;
  updatedAt: string;
}

// Innovation Hub / ForgeLab Types
export interface Idea {
  id: string;
  projectId?: string;
  title: string;
  description: string;
  category: 'product' | 'service' | 'process' | 'business-model' | 'technology';
  author: string;
  authorAvatar?: string;
  authorType: 'diaspora' | 'local' | 'student';
  authorLocation: string;
  stage: 'ideation' | 'validation' | 'development' | 'pilot' | 'scaling';
  status: 'active' | 'on-hold' | 'completed' | 'archived';
  tags: string[];
  upvotes: number;
  comments: number;
  views: number;
  feasibility: number;
  impact: number;
  effort: number;
  isBookmarked: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface CoCreationRoom {
  id: string;
  projectId?: string;
  name: string;
  description: string;
  type: 'brainstorming' | 'design' | 'development' | 'review' | 'planning';
  members: Array<{
    id: string;
    name: string;
    avatar?: string;
    role: string;
    isOnline: boolean;
  }>;
  files: Array<{
    id: string;
    name: string;
    type: string;
    size: string;
    uploadedBy: string;
  }>;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface ProjectWorkspace {
  id: string;
  projectId: string;
  name: string;
  description: string;
  members: Array<{
    id: string;
    name: string;
    avatar?: string;
    role: string;
  }>;
  files: Array<{
    id: string;
    name: string;
    type: string;
    size: string;
    uploadedBy: string;
  }>;
  createdAt: string;
  updatedAt: string;
}

export interface BuildTool {
  id: string;
  projectId: string;
  name: string;
  type: 'code-editor' | 'design-tool' | 'database' | 'api' | 'deployment';
  status: 'active' | 'inactive';
  config: Record<string, any>;
  createdAt: string;
  updatedAt: string;
}

// Database Schema
export interface Database {
  users: UserProfile[];
  projects: Project[];
  opportunities: Opportunity[];
  campaigns: Campaign[];
  tasks: Task[];
  milestones: Milestone[];
  feedItems: FeedItem[];
  userActions: UserAction[];
  adminHighlights: AdminHighlight[];
  connectionRequests: ConnectionRequest[];
  messages: Message[];
  sessions: Session[];
  uploadedFiles: UploadedFile[];
  voiceNotes: VoiceNote[];
  learningContent: LearningContent[];
  recordings: Recording[];
  deliverables: Deliverable[];
  certificates: Certificate[];
  liveSessions: LiveSession[];
  researchSources: ResearchSource[];
  researchNotes: ResearchNote[];
  dataSets: DataSet[];
  stakeholders: Stakeholder[];
  impactStories: ImpactStory[];
  communityEvents: CommunityEvent[];
  ideas: Idea[];
  coCreationRooms: CoCreationRoom[];
  projectWorkspaces: ProjectWorkspace[];
  buildTools: BuildTool[];
}

