services:
  - type: web
    name: ispora-backend
    env: node
    plan: free
    buildCommand: npm install && node setup-database.js && node setup-production-db.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_CLIENT
        value: sqlite3
      - key: DB_FILENAME
        value: ./data/ispora.db
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://ispora.app
      - key: CORS_ORIGIN
        value: https://ispora.app
