import express from 'express';
import { authenticate, optionalAuth, AuthRequest } from '../middleware/auth.js';
import { DatabaseService } from '../database/database.js';
import { v4 as uuidv4 } from 'uuid';
import { Project, FeedItem } from '../types/index.js';

const router = express.Router();
const db = DatabaseService.getInstance();

// Get all projects
router.get('/', optionalAuth, (req, res) => {
  try {
    const { status, category, university, search } = req.query;
    
    let projects = db.getProjects();
    
    // Filter by status
    if (status) {
      projects = projects.filter(p => p.status === status);
    }
    
    // Filter by category
    if (category) {
      projects = projects.filter(p => p.category === category);
    }
    
    // Filter by university
    if (university) {
      projects = projects.filter(p => p.university === university);
    }
    
    // Search
    if (search) {
      const searchLower = (search as string).toLowerCase();
      projects = projects.filter(p => 
        p.title.toLowerCase().includes(searchLower) ||
        p.description.toLowerCase().includes(searchLower) ||
        p.tags.some(tag => tag.toLowerCase().includes(searchLower))
      );
    }
    
    res.json(projects);
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// Get project by ID
router.get('/:projectId', optionalAuth, (req, res) => {
  try {
    const project = db.getProjectById(req.params.projectId);
    if (!project) {
      return res.status(404).json({ error: 'Project not found' });
    }
    res.json(project);
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// Create project
router.post('/', authenticate, async (req: AuthRequest, res) => {
  try {
    const projectData = req.body;
    const user = db.getUserById(req.user!.id);
    
    if (!user) {
      return res.status(404).json({ error: 'User not found' });
    }
    
    const now = new Date().toISOString();
    const project: Project = {
      id: uuidv4(),
      title: projectData.title,
      description: projectData.description,
      status: projectData.status || 'active',
      startDate: projectData.startDate,
      deadline: projectData.deadline,
      category: projectData.category,
      aspiraCategory: projectData.aspiraCategory || 'mentorships',
      tags: projectData.tags || [],
      team: projectData.team || [],
      university: projectData.university,
      location: projectData.location,
      authorId: user.id,
      authorName: user.name,
      projectType: projectData.projectType,
      priority: projectData.priority,
      mentorshipConnection: projectData.mentorshipConnection,
      isPublic: projectData.isPublic !== false,
      teamMembers: projectData.teamMembers,
      diasporaPositions: projectData.diasporaPositions,
      progress: projectData.progress || 0,
      metrics: projectData.metrics,
      createdAt: now,
      updatedAt: now,
    };
    
    const created = db.createProject(project);
    
    // Automatically create a feed item for the new project
    if (created.isPublic) {
      const feedItem: FeedItem = {
        id: `feed_project_${created.id}`,
        type: 'project',
        title: `New Project: ${created.title}`,
        description: created.description,
        timestamp: now,
        likes: 0,
        location: created.location || '',
        category: created.category || created.projectType || '',
        urgent: !!(created.status === 'active' && created.deadline && new Date(created.deadline) < new Date(Date.now() + 7 * 24 * 60 * 60 * 1000)),
        deadline: created.deadline,
        isLive: false,
        isPinned: false,
        isAdminCurated: false,
        authorId: created.authorId,
        authorName: created.authorName,
        authorAvatar: user.avatar,
        projectId: created.id,
        metadata: {
          university: created.university,
          tags: created.tags,
          aspiraCategory: created.aspiraCategory,
          team: created.team,
          status: created.status,
        },
        visibility: 'public',
        significance: created.status === 'active' ? 'high' : 'medium',
        isAutoGenerated: true,
      };
      db.createFeedItem(feedItem);
      
      // Emit real-time feed update via WebSocket
      try {
        const { emitFeedItemAdded } = await import('../websocket/websocket.js');
        emitFeedItemAdded(feedItem);
      } catch (error) {
        console.warn('Failed to emit feed item via WebSocket:', error);
      }
    }
    
    res.status(201).json(created);
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// Update project
router.put('/:projectId', authenticate, (req: AuthRequest, res) => {
  try {
    const project = db.getProjectById(req.params.projectId);
    if (!project) {
      return res.status(404).json({ error: 'Project not found' });
    }
    
    // Check if user is author or team member
    if (project.authorId !== req.user!.id && !project.team.some(m => m.id === req.user!.id)) {
      return res.status(403).json({ error: 'Not authorized to update this project' });
    }
    
    const updated = db.updateProject(req.params.projectId, req.body);
    res.json(updated);
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// Join project
router.post('/:projectId/join', authenticate, (req: AuthRequest, res) => {
  try {
    const { role, area } = req.body;
    const project = db.getProjectById(req.params.projectId);
    
    if (!project) {
      return res.status(404).json({ error: 'Project not found' });
    }
    
    const user = db.getUserById(req.user!.id);
    if (!user) {
      return res.status(404).json({ error: 'User not found' });
    }
    
    // Add user to team if not already there
    if (!project.team.some(m => m.id === user.id)) {
      project.team.push({
        id: user.id,
        name: user.name,
        role: role || 'participant',
        avatar: user.avatar,
      });
      db.updateProject(project.id, { team: project.team });
    }
    
    res.json({ success: true, message: 'Successfully joined project' });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// Get workspace data (tasks and milestones)
router.get('/:projectId/workspace', authenticate, (req, res) => {
  try {
    const tasks = db.getTasks(req.params.projectId);
    const milestones = db.getMilestones(req.params.projectId);
    
    res.json({
      tasks,
      milestones,
      isLoading: false,
    });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

export default router;

